### ISSUE TITLE
Few drawbacks needs to improve

### ISSUE THREAD

**Issue by hiteshsarsava** [SimformSolutionsPvtLtd/SSJetPackComposeProgressButton#46]
**Is your feature request related to a problem? Please describe.**
1. **The button should be disable when it is in loading state**, There is no meaning of showing progress indicator and user can still able to request the operation on click of button.
2. There should be no mandatory pass the width and height arguments. What if user wants to set **wrap content** or **fillMaxWidth()**(**match parent**) of button size. This is not proper use case where user needs to calculate the width and height of the button and pass as argument. 
3. There is no modifier argument for button itself.

**Comment by ShwetaChauhan18** [comment]
Thanks, @hiteshsarsava to draw attention. We will check.

**Comment by purvesh-d** [comment]
Replies to above points:

1. Issue is resolved and PR merged.
2. Mandatory passing the width and height is requierd because we are using it to animate button height/width while button is in loading state. If there is a way to do that without fixed height/width then please feel free to share.
3. We are using modifier to to animate button size so if we provide modifier argument then animation will not work when user change size related property.  So to give customisation most of all the properties of modifier we have added in SSJetPackComposeProgressButton argument as mention below.

- Background/ Colors
- Padding
- Border
- Alpha
- Click action
If you want to use more properties of modifier for customisation then please provide us that properties so we can plan to add it in upcoming release.
